### ISSUE TITLE
Push rejected, no Cedar-supported app detected

### ISSUE THREAD

**Issue by bozzltron** [alex88/heroku-buildpack-vips#21]
My heroku deployment works fine without buildpacks.  When I add your build pack heroku fails to detect that I have a node app.  Any suggestions?   Thank you.

**Comment by alex88** [comment]
@bozzltron how have you added my buildpack?

**Comment by bozzltron** [comment]
$ heroku buildpacks
1. https://github.com/alex88/heroku-buildpack-vips.git#7.40.11.0
2. https://github.com/heroku/heroku-buildpack-nodejs.git

**Comment by alex88** [comment]
You've to use https://github.com/ddollar/heroku-buildpack-multi as I wrote in the readme

**Comment by bozzltron** [comment]
Perfect!  Thank you.
