### ISSUE TITLE
bin/detect: print a human-readable framework name to stdout

### ISSUE THREAD

**Issue by jonathanong** [alex88/heroku-buildpack-vips#24]
https://devcenter.heroku.com/articles/buildpack-api#bin-detect

otherwise this buildpack files if used within an `app.json`'s `app.buildpacks[]`.

**Comment by alex88** [comment]
What you mean with "otherwise this buildpack files if used"? Actually this buildpack has to be used with https://github.com/ddollar/heroku-buildpack-multi so not as a buildpack alone

**Comment by jonathanong** [comment]
Oops sorry. "Failed" not "files".

Yes it's fine with the multipack but it won't work in app.json without it because it doesn't echo its own name. I don't know why heroku made it a requirement but it's an  easy fix.

**Comment by jonathanong** [comment]
App.json is used for review apps btw

**Comment by mjackson** [comment]
Fixed in #25
