### ISSUE TITLE
messes up my other buildpack's PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by jonathanong** [alex88/heroku-buildpack-vips#7]
https://github.com/ddollar/heroku-buildpack-apt/issues/11

seems like if i use this package with `heroku-buildpack-apt`, my `phash` installation fails. however, if i remove this buildpack, everything will build perfectly. do you know what's wrong?

**Comment by moustacheful** [comment]
Hi, @jonathanong I see this was fixed but I'm seeing the exact same problem (even using the same buildpacks and packages). 
I'm having trouble getting `pHash` to work along with `buildpack-vips`.
I tried looking for pHash.pc and found it in `/app/.apt/usr/lib/pkgconfig` so i set that as the `PKG_CONFIG_PATH`. Still no dice.

How did you get it to work?

**Comment by jonathanong** [comment]
https://github.com/mgmtio/video-phash-service

This is the only place I'm using phash right now... Sorry I haven't used phash and this build pack in a while
